print("Lists")
list1 = ["Kevin","Laura", "Ari", "Marc","Erik", "Santi", "Pol", "Roger"]
print(list1)
print("The index of the elements starts at 0")
print("At the first list, kevin would be the 0 Index, and Ari, would be the second")
print("in order it would be (using the first Capital to enumerate):")
print("K=0, L=1, A=2, M=3, E=4, S=5, P=6 and R=7")
print("to get a particular element inside the list,")
print("we have to write the name of the list, and between square brackets [ ],")
print("we're going to put the index number of the element that we want to show")
print("for example, we want Erik, [4], and Laura [1]")
print(list1[4])
print(list1[1])
print("We can also print more than an element that we want")
print("With the two points symbol :, we're saying that we want to select a range of elements,")
print("if we don't indicate the final or the beginning, by default it will select all the elements until ypu number")
print(list1[3:])
print(list1[:5])
print(list1[3:6])
list2 = (1,"Laura", True,"Kevin",2, False)
print("It doesn't matter what it's inside the list strings, numbers. boolean. It always be indexed like that")
print(list2)
print("We can also get values starting from the end of the list,")
print("we only have to put a negative index number [-2]")
print("But we have to be carefully, because when we start from the end,")
print("the index number starts at 0,")
print("example starting from the end:")
print("K=-8, L=-7, A=-6, M=-5, E=-4, S=-3, P=-2 and R=-1")
print(list1[-3])
print("If we would like to combine two list or more, you can use the extend function,")
print("all the functions, (name of the list/variable).(name of the function)")
list3 = [1,5,7,2,85,654,8]
print(list3)
list1.extend(list2)
list1.extend(list3)
print(list1)
print("Can we combine more than two lists in the same extend function?")

print(list2)
print("We can also change one element from the list")
list4 = ["Kevin","Laura"]
list4[1]="Text"
print(list4)
print("We can also put one element in one list, if we don't indicate where we want it,")
print("by default will put it at the end of the list. append function")
list4.append("Poppy")
print(list4)
list4.insert(1,"Hello world")
print(list4)
print("to remove one element")
list4.remove("Kevin")
print(list4)
print("to clear the list")
list4.clear()
print(list4)
print("to remove the last element, pop function")
friends = ["Kevin","Laura","Ari", "Marc","Erik","Santi","Pol","Pol","Roger"]
print(friends)
friends.pop()
print(friends)
print("to search an element, we can use the index function, that it will return the index value of the element that "
      "we're searching")
print(friends.index("Ari"))
print("to count how many times an element appears, we're going to use the count function")
print(friends.count("Pol"))
friends2 = ["Kevin","Laura","Ari", "Marc","Erik","Santi","Pol","Pol","Roger"]
print(friends2)
friends2.sort()
print(friends2)
list3.sort()
print(list3)
friends2.reverse()
print(friends2)

