print("VIRUS")
print("VIRUS")
print("VIRUS")
print("VIRUS")
print(" ")
print(" ")
print(" ")
input("Do you want to delete all your store...?  ")
print(" ")
print(" ")
print(" ")
print("Deleting the storage ")
print(" ")
print(" ")
print(" ")
print("   \   /      \   /   ")
print("    \ /        \ /    ")
print("     X          X     ")
print("    / \        / \    ")
print("   /   \      /   \   ")
print("                      ")
print("                      ")
print("     |---------|      ")
print("     |_|_|_|_|_|      ")
input("Do you think i'll let you do what you want... JAJAJA")
print(" ")

print(input("Shutting down... "))
