name = input("Enter your name:")
age = input("Enter your age:")
print("Hey You! Yes you, " + name +"!")
print("Hey, you're " + age + " you're an adlut, so...")
print(" ")
fac1 = input("Do you like baloons?")
print(" ")
print("What was you thinking I'm gonna ask...")
print(" ")
print("Ok, let me tell you a story sweety,")
print(" ")
print("Once upon a time, really long, long time ago.")
print("In a small village in, in... Ups, I forget the village name. :O ")
print(" ")
vila = input("Do you remmember the name?, Come on! tell it me!! Please... would you mind telling me the name of the village: ")
print("Aha! yes, that was it. " + vila + " was the name. So, let me continue.\nIn " + vila + " used to live a man, a very tall man.")
print(" ")
heigh = input("Okei, try to guess ehat was his heigh...")
print(" ")
print("Uhau!, yes, " + heigh + " was his heigh. Wait a moment, did I tell you that story?,Oh... Well, then, if you already know that story, ")
print("You'll have to wait until I control the if functions JEJEJE :P")
print("But before we go... I'm going to make you a magic trick :D. You have to tell me two numbers.")
print("But, let me tell you a clue, you should give big numbers,\nvery big numbers, about the thousand order, and you shouldn't give me enough time to think!")
print("Because i'm going to make your first number to the power of your second number,")
print("and divide the result by your age multiplied by the men's heigh.")
num1 = input("Number 1 is?")
num2 = input("Number 2 is?")
result = (pow(float(num1), float(num2))/float(age))
print(" ")
print("Okei.. uhmmmmmmmmm...")
print(3)
print(2)
print("Tachan! It's " + str(result))
final_answer = input("did you like it?")
print("Bye bye Stupid")